CREATE TABLE IF NOT EXISTS "uris" (
"id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
"aria2_gid" INTEGER NOT NULL ,
"uri" TEXT,
"save_path" TEXT,
"status" VARCHAR(25),
"created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP
);
