CREATE TABLE IF NOT EXISTS "uris" (
"id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
"uri" TEXT NOT NULL  UNIQUE ,
"aria2_gid" INTEGER NOT NULL ,
"save_path" TEXT,
"created_at" TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
"updated_at" TIMESTAMP
);
